# Generated by Django 5.0.2 on 2024-04-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_api", "0003_remove_teamschatmessage_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
