# Generated by Django 5.0.2 on 2024-04-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_api", "0004_alter_meeting_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="name",
            field=models.CharField(default="Reunião", max_length=255),
            preserve_default=False,
        ),
    ]
