# Generated by Django 5.0.2 on 2024-05-14 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_api", "0009_project_assigned_to_alter_project_creatorid"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
