# Generated by Django 5.0.2 on 2024-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0010_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='project_tasks', to='crm_api.task'),
        ),
    ]
