# Generated by Django 5.0.2 on 2024-05-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_api", "0010_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisors",
            field=models.ManyToManyField(
                related_name="subordinates", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
