# Generated by Django 5.0.2 on 2024-05-24 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm_api", "0011_meeting_owner_user_supervisors"),
        ("crm_api", "0011_project_tasks"),
    ]

    operations = []
